apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
    - name: apache
      image: httpd
      env:
        # Define the environment variable
        - name: CONTENT
          valueFrom:
            configMapKeyRef:
              name: q5
              # Specify the key associated with the value
              key: special.how
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password

